name: Daily Hijacklibs

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 AM every day
  workflow_dispatch:

jobs:
  fetch-ip-ranges:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Clone HijackLibs repository
        run: git clone https://github.com/wietze/HijackLibs ./HijackLibs
        
      - name: Run HijackLibs script
        run: python Lists/Hijacklibs/hijacklibs.py
        
      - name: List files in the root directory
        run: ls -la

      - name: List files in the Lists/TOR directory
        run: ls -la Lists/Hijacklibs

      - name: Move output files to correct directory (if necessary)
        run: |
          mv hijacklibs_list.csv Lists/Hijacklibs/ || echo "File not found in root."

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Lists/Hijacklibs/hijacklibs_list.csv
          git commit -m "Update daily hijacklibs list" --allow-empty
          git push

      - name: Upload Results to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hijacklibs
          path: Lists/Hijacklibs/hijacklibs_list.csv
